name: RHPB_optimization
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - seaborn
  - pyyaml
  - scikit-learn
  - matplotlib
  - pip
  - setuptools
  - build
  - pip:
      - botorch
      - quantecon
      - pyinstaller